const $=(q,el=document)=>el.querySelector(q), $$=(q,el=document)=>[...el.querySelectorAll(q)];
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const events=[
{id:'moon',category:'cinema',label:'映画上映',date:'2026.11.28 SAT',time:'18:30 開場 / 19:00 開始',title:'はじめましての上映会',description:'こまどの幕開けに、一本の映画を。上映作品は近日お知らせします。',body:'初めてお店に灯りがともる夜。上映の前も後も、一杯のコーヒーと一緒にお過ごしください。\n上映作品・上映時間は準備が整い次第お知らせします。現在は開催イメージを紹介するサンプルです。',price:1500,capacity:4},
{id:'jazz',category:'music',label:'音楽',date:'2026.11.29 SUN',time:'17:30 開場 / 18:00 開始',title:'日曜の夕暮れ、ふたりのジャズ。',description:'ピアノとギターをすぐそばで。小さな喫茶で楽しむ生演奏。',body:'大きなステージはありません。いつもの喫茶の椅子で、近くから届く音を楽しむ日曜日。\n出演者と演奏内容は正式公開時にご案内します。現在は開催イメージを紹介するサンプルです。',price:2800,capacity:4},
{id:'coffee',category:'workshop',label:'ワークショップ',date:'2026.12.05 SAT',time:'10:30 開場 / 11:00 開始',title:'朝のコーヒー教室',description:'豆を挽くところから、ゆっくりと。はじめての方もどうぞ。',body:'お湯を注いで、香りを待って。一杯のコーヒーをおいしく淹れる、小さなワークショップです。\n道具はお店で用意する想定です。講師や内容は正式公開時にご案内します。',price:2000,capacity:2}];
const defaultArticles=[
{id:'opening',date:'2026-10-01',category:'お知らせ',title:'11月末、こまどがオープンします。',body:'映画と、喫茶と、小さな集まり。\nシアター喫茶「こまど」は、11月末の開店を目指して準備中です。\n一本の映画を観に来る日も、コーヒーだけを飲みに来る日も。好きなものをきっかけに、気軽に立ち寄れる場所をつくります。\n正式な開店日・所在地・営業日時は、準備が整い次第こちらでご案内します。\n※店名を含め、制作プレビュー用の仮情報です。'},
{id:'about',date:'2026-10-03',category:'読みもの',title:'スクリーンのそばに、喫茶の席を。',body:'映画のあと、すぐに帰るのが少し惜しい。\nそんなときに、コーヒーを飲みながらもう少し過ごせる席があったら。\nこまどでは、映画のある日もない日も、それぞれの時間を楽しめる店を目指しています。上映会のほかにも、小さなライブやワークショップを開いていく予定です。\n店内の椅子やメニューのことも、これから少しずつお伝えしていきます。\n※提案用の記事サンプルです。'},
{id:'rental',date:'2026-10-05',category:'お知らせ',title:'小さな上映会や貸切のご相談について。',body:'好きな映画を一緒に観る会。音楽を届ける夜。誰かに教えたくなるワークショップ。\nこまどでは、空間を貸し出す準備を進めています。\nご希望の日程や人数、利用内容をお知らせいただき、設備と条件を確認してから正式な予約へ進む予定です。\n現在のカレンダー・定員・料金はサンプルです。実際のご相談受付は正式公開後に開始します。'}];
let articles=structuredClone(defaultArticles),storageAvailable=true,activeJournalFilter='all';
try{const saved=JSON.parse(localStorage.getItem('komado.articles.v1')||'null');if(Array.isArray(saved)&&saved.every(a=>a&&['id','date','category','title','body'].every(k=>typeof a[k]==='string')&&['お知らせ','読みもの'].includes(a.category)))articles=saved;}catch{storageAvailable=false;}
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
function animateState(el,move=false){el.getAnimations().forEach(a=>a.cancel());if(!reducedMotion.matches)el.animate([{opacity:.55,transform:move?'translateY(4px)':'none'},{opacity:1,transform:'none'}],{duration:move?220:160,easing:'cubic-bezier(.2,.7,.2,1)'});}
const titleMarkup=e=>esc(e.title);
let lastFocus;const dialog=$('#dialog');
function openDialog(html){if(!dialog.open)lastFocus=document.activeElement;$('#dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal();document.body.classList.add('body-lock');animateState($('#dialog-content'),true);const title=$('#dialog-title');if(title){title.tabIndex=-1;title.focus();}}
function closeDialog(){dialog.close();}
dialog.addEventListener('close',()=>{document.body.classList.remove('body-lock');$('#dialog-content').getAnimations().forEach(a=>a.cancel());lastFocus?.focus();});$('.dialog-close').onclick=closeDialog;
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function notify(message){const el=$('.toast');el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),3500);}
const menu=$('.menu-toggle');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');$('#navigation').classList.toggle('open',open);};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.click();menu.focus();}});
$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')&&menu.getAttribute('aria-expanded')==='true')menu.click();});
function renderEvents(filter='all'){
 $$('[data-event-list]').forEach(list=>{
  list.innerHTML=events.filter(e=>filter==='all'||e.category===filter).map(e=>{
   const parts=e.date.split(/[. ]/),day=e.id==='jazz'?'日':'土',start=e.time.split(' / ')[1].replace(' 開始','');
   return `<article class="event-card"><time class="event-date" datetime="${parts.slice(0,3).join('-')}"><span>${Number(parts[1])}月</span><strong>${parts[2]}</strong><small>${day}曜日</small></time><div class="event-info"><span class="event-category">${e.label}</span><h3>${titleMarkup(e)}</h3><p class="event-summary">${esc(e.description)}</p></div><div class="event-meta"><span>${start} 開始</span><strong>¥${e.price.toLocaleString()}</strong><small>1名・税込（仮）</small></div><button class="event-link" data-event="${e.id}" aria-label="${esc(e.title)} の詳細・予約">詳細・予約 <span aria-hidden="true">↗</span></button></article>`;
  }).join('');
 });
}
$$('[data-filter]').forEach(btn=>btn.onclick=()=>{$$('[data-filter]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});renderEvents(btn.dataset.filter);});
function showEvent(id,count=1){const e=events.find(e=>e.id===id);if(!e)return;openDialog(`<p class="eyebrow">${e.label} — EVENT DETAILS</p><h2 id="dialog-title">${titleMarkup(e)}</h2><p>${e.body}</p><dl class="detail-meta"><dt>開催日</dt><dd>${e.date}</dd><dt>時間</dt><dd>${e.time}</dd><dt>料金</dt><dd>¥${e.price.toLocaleString()} / 1名・税込（仮）</dd></dl><div class="notice">予約体験のデモです。席の確保・決済は行いません。</div><form id="event-form"><label>ご予約人数<select name="count">${Array.from({length:e.capacity},(_,i)=>`<option value="${i+1}" ${count===i+1?'selected':''}>${i+1}名</option>`).join('')}</select></label><p id="booking-total">合計 ¥${(e.price*count).toLocaleString()}（税込・仮）</p><button class="button light" type="submit">予約内容を確認 <span>↗</span></button></form>`);const form=$('#event-form');form.elements.count.onchange=()=>$('#booking-total').textContent=`合計 ¥${(Number(form.elements.count.value)*e.price).toLocaleString()}（税込・仮）`;form.onsubmit=ev=>{ev.preventDefault();showBookingConfirmation(e,Number(form.elements.count.value));};}
function showBookingConfirmation(e,count){openDialog(`<p class="eyebrow">RESERVATION PREVIEW</p><h2 id="dialog-title"><span class="keep-phrase">予約内容を</span><span class="keep-phrase">ご確認ください。</span></h2><dl class="detail-meta"><dt>イベント</dt><dd>${e.title}</dd><dt>開催日</dt><dd>${e.date}</dd><dt>時間</dt><dd>${e.time}</dd><dt>人数</dt><dd>${count}名</dd><dt>合計</dt><dd>¥${(e.price*count).toLocaleString()}（税込・仮）</dd></dl><div class="notice">予約体験のデモです。実際の予約は成立しません。</div><button class="button light" id="finish-demo">予約のデモを完了 <span>↗</span></button><button class="button outline" id="back-booking">人数を選び直す <span>←</span></button>`);$('#back-booking').onclick=()=>showEvent(e.id,count);$('#finish-demo').onclick=()=>{openDialog(`<div class="success-icon">✓</div><p class="eyebrow">DEMO COMPLETED</p><h2 id="dialog-title">予約の流れを体験しました。</h2><p>ご選択内容：${e.title}\n${count}名 / ¥${(e.price*count).toLocaleString()}（税込・仮）</p><div class="notice">実際の予約は作成されていません。お支払いや確認メールの送信も行っていません。</div><button class="button light" id="done-close">イベントへ戻る <span>↗</span></button>`);$('#done-close').onclick=closeDialog;};}
function renderJournal(){$$('[data-journal-list]').forEach(list=>{const limit=Number(list.dataset.limit)||1000;list.innerHTML=[...articles].filter(a=>activeJournalFilter==='all'||a.category===activeJournalFilter).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,limit).map(a=>`<button class="journal-row" data-article="${esc(a.id)}"><time datetime="${esc(a.date)}">${esc(a.date.replaceAll('-','.'))}</time><span class="journal-tag">${esc(a.category)}</span><span class="journal-title">${esc(a.title).replace(/(オープンします。)$/,'<span class="keep-phrase">$1</span>')}</span><span class="arrow">↗</span></button>`).join('')||'<p>該当する記事はありません。</p>';});}
function showArticle(id){const a=articles.find(a=>a.id===id);if(a)openDialog(`<p class="eyebrow">${esc(a.date.replaceAll('-','.'))} / ${esc(a.category)}</p><h2 id="dialog-title">${esc(a.title).replace(/(こまどが|オープンします。|喫茶の席を。|ご相談について。)/g,'<span class="keep-phrase">$1</span>')}</h2><div class="article-body">${esc(a.body)}</div>`);}
$$('[data-journal-filter]').forEach(btn=>btn.onclick=()=>{activeJournalFilter=btn.dataset.journalFilter;$$('[data-journal-filter]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});renderJournal();});
document.addEventListener('click',e=>{const event=e.target.closest('[data-event]'),article=e.target.closest('[data-article]'),privacy=e.target.closest('[data-privacy]');if(event)showEvent(event.dataset.event);if(article)showArticle(article.dataset.article);if(privacy)openDialog('<p class="eyebrow">PRIVACY — PREVIEW</p><h2 id="dialog-title">プライバシーについて</h2><p>この制作プレビューでは、お問い合わせ内容をサーバーへ送信・保存しません。予約操作もデモです。\n\n記事管理デモで保存した記事は、このブラウザーのローカルストレージに保存されます。記事本文に個人情報や機密情報を入力しないでください。サイトデータを削除すると記事も削除されます。\n\n書体の表示にGoogle Fontsを使用し、フォント取得時に同サービスへ接続します。\n\n正式公開時には、実際の運営者情報・利用目的・保存期間・お問い合わせ窓口を定めたプライバシーポリシーを掲載します。</p>');});
const editor=$('#editor');
if(editor){const form=$('#editor-form');function refreshOptions(){$('#edit-id').innerHTML='<option value="">新しい記事を追加</option>'+articles.map(a=>`<option value="${esc(a.id)}">${esc(a.title)}</option>`).join('');}function clear(){form.reset();form.elements.date.value=new Date().toLocaleDateString('sv-SE');}refreshOptions();clear();$('#open-editor').onclick=()=>{editor.hidden=!editor.hidden;$('#open-editor').setAttribute('aria-expanded',String(!editor.hidden));if(!editor.hidden){editor.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'start'});$('#edit-id').focus({preventScroll:true});}};$('#edit-id').onchange=()=>{const a=articles.find(a=>a.id===$('#edit-id').value);if(a){for(const k of ['title','category','date','body'])form.elements[k].value=a[k];}else clear();};form.onsubmit=e=>{e.preventDefault();const data=new FormData(form),title=String(data.get('title')).trim(),body=String(data.get('body')).trim();if(!title||!body){$('#editor-status').textContent='タイトルと本文を入力してください。';return;}const id=$('#edit-id').value||crypto.randomUUID(),article={id,title,body,category:String(data.get('category')),date:String(data.get('date'))};const updated=articles.some(a=>a.id===id)?articles.map(a=>a.id===id?article:a):[...articles,article];try{localStorage.setItem('komado.articles.v1',JSON.stringify(updated));articles=updated;renderJournal();refreshOptions();$('#edit-id').value=id;$('#editor-status').textContent='このブラウザーに保存しました。サイトへの公開は行われていません。';notify('記事をこのブラウザーに保存しました');}catch{$('#editor-status').textContent='保存できませんでした。ブラウザーの保存設定や空き容量を確認してください。';}};$('#export-content').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,articles},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='komado-articles.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};if(!storageAvailable)$('#editor-status').textContent='保存データを読み込めなかったため初期記事を表示しています。';}
let calendarDate=new Date(2026,10,1),selectedDate='';const calendar=$('#calendar-grid'),firstDate=new Date(2026,10,28),lastDate=new Date(2027,10,30);
function availability(day){if(day<firstDate||day>lastDate||day.getDay()===2)return 0;return day.getDate()%3===0?1:2;}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#calendar-month').textContent=`${y}年 ${m+1}月`;$('[data-month="-1"]').disabled=y===2026&&m===10;$('[data-month="1"]').disabled=y===2027&&m===10;calendar.innerHTML=Array.from({length:new Date(y,m,1).getDay()},()=>'<span></span>').join('')+Array.from({length:new Date(y,m+1,0).getDate()},(_,i)=>{const available=availability(new Date(y,m,i+1)),iso=`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return `<button class="calendar-day ${selectedDate===iso?'selected':''}" data-date="${iso}" ${available?'':'disabled'} aria-pressed="${selectedDate===iso}" aria-label="${y}年${m+1}月${i+1}日 ${available===2?'空きあり':available===1?'一部空き':'受付なし'}">${i+1}<small>${available===2?'○':available===1?'△':'—'}</small></button>`;}).join('');}
const timeLabel=minutes=>`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;
const timeOptions=(from,to,selected)=>Array.from({length:(to-from)/30+1},(_,i)=>from+i*30).map(value=>`<option value="${timeLabel(value)}" ${value===selected?'selected':''}>${timeLabel(value)}</option>`).join('');
function renderRentalPicker(){
 const partial=availability(new Date(`${selectedDate}T12:00:00`))===1,startMin=partial?840:600,endMax=partial?1020:1260,availabilityLabel=partial?'この日は 14:00〜17:00 のみ利用できます。':'この日は 10:00〜21:00 の間で選べます。';
 $('#time-slots').innerHTML=`<form id="rental-picker" class="rental-picker"><div class="picker-heading"><div><p class="eyebrow">REQUEST DETAILS</p><h4>${selectedDate.replaceAll('-',' / ')} の利用時間</h4></div><span>30分単位・3時間から</span></div><p class="availability-note" role="status">${availabilityLabel}</p><div class="time-selects"><label>開始時間<select id="rental-start" name="start" required>${timeOptions(startMin,endMax-180,startMin)}</select></label><span aria-hidden="true">→</span><label>終了時間<select id="rental-end" name="end" required>${timeOptions(startMin+180,endMax,startMin+180)}</select></label></div><div class="rental-fields"><label>利用目的<select name="purpose" required><option value="">選択してください</option><option>自主上映・鑑賞会</option><option>ライブ・演奏・朗読</option><option>ワークショップ・講座</option><option>展示・撮影</option><option>その他</option></select></label><label>利用人数<select name="guests" required><option value="">選択してください</option>${Array.from({length:20},(_,i)=>`<option value="${i+1}">${i+1}名</option>`).join('')}</select></label></div><label>お問い合わせ内容<textarea name="details" rows="4" required maxlength="1000" placeholder="企画の内容、使用したい設備、搬入の有無などをご記入ください。"></textarea></label><div class="rental-total"><span>参考料金</span><strong id="rental-total" aria-live="polite">¥12,000</strong><small>3時間・税込（仮）</small></div><button class="button" type="submit">選択内容を確認する <span>↗</span></button><p class="picker-note">空き状況と料金はサンプルです。この操作では予約は確定しません。</p></form>`;
 const form=$('#rental-picker'),start=form.elements.start,end=form.elements.end,total=$('#rental-total');
 const updateEnd=()=>{const startValue=Number(start.value.slice(0,2))*60+Number(start.value.slice(3));const current=end.value;end.innerHTML=timeOptions(startValue+180,endMax,Math.max(startValue+180,Number(current.slice(0,2))*60+Number(current.slice(3))||0));if(!end.value)end.selectedIndex=0;updateTotal();};
 const updateTotal=()=>{const startValue=Number(start.value.slice(0,2))*60+Number(start.value.slice(3)),endValue=Number(end.value.slice(0,2))*60+Number(end.value.slice(3)),hours=(endValue-startValue)/60;total.textContent=`¥${(hours*4000).toLocaleString()}`;total.nextElementSibling.textContent=`${hours}時間・税込（仮）`;};
 start.addEventListener('change',updateEnd);start.addEventListener('input',updateEnd);end.addEventListener('change',updateTotal);end.addEventListener('input',updateTotal);updateTotal();
 form.onsubmit=e=>{e.preventDefault();const data=new FormData(form),startValue=String(data.get('start')),endValue=String(data.get('end')),purpose=String(data.get('purpose')),guests=String(data.get('guests')),details=String(data.get('details')).trim(),hours=(Number(endValue.slice(0,2))*60+Number(endValue.slice(3))-Number(startValue.slice(0,2))*60-Number(startValue.slice(3)))/60,price=hours*4000;if(!purpose||!guests||!details)return;const query=new URLSearchParams({date:selectedDate,start:startValue,end:endValue,purpose,guests,details});openDialog(`<p class="eyebrow">SPACE RENTAL — REQUEST PREVIEW</p><h2 id="dialog-title">利用内容をご確認ください。</h2><dl class="detail-meta"><dt>ご希望日</dt><dd>${selectedDate.replaceAll('-',' / ')}</dd><dt>利用時間</dt><dd>${startValue} – ${endValue}（${hours}時間）</dd><dt>利用目的</dt><dd>${esc(purpose)}</dd><dt>利用人数</dt><dd>${esc(guests)}名</dd><dt>参考料金</dt><dd>¥${price.toLocaleString()}（仮・税込）</dd></dl><div class="request-note"><span>お問い合わせ内容</span><p>${esc(details)}</p></div><div class="notice">予約相談のデモです。空き状況の確保や予約の確定は行われません。</div><a class="button light" href="./contact.html?${query}">お問い合わせへ進む <span>↗</span></a>`);};
}
if(calendar){renderCalendar();$$('[data-month]').forEach(btn=>btn.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+Number(btn.dataset.month));selectedDate='';renderCalendar();animateState(calendar);$('#time-slots').innerHTML='<p class="muted">カレンダーから日付を選んでください。</p>';});calendar.onclick=e=>{const btn=e.target.closest('[data-date]');if(!btn||btn.disabled)return;selectedDate=btn.dataset.date;renderCalendar();calendar.querySelector(`[data-date="${selectedDate}"]`).focus({preventScroll:true});renderRentalPicker();animateState($('#time-slots'));};}
const contact=$('#contact-form');if(contact){const params=new URLSearchParams(location.search);if(params.has('date')){const start=params.get('start')||'',end=params.get('end')||'',purpose=params.get('purpose')||'',guests=params.get('guests')||'',details=params.get('details')||'';contact.elements.type.value='スペースレンタルについて';contact.elements.message.value=`希望日：${params.get('date')}\n希望時間：${start}${end?` – ${end}`:''}\n利用目的：${purpose}\n予定人数：${guests}${guests?'名':''}\nお問い合わせ内容：${details}`;const summary=document.createElement('section');summary.className='inquiry-summary';summary.setAttribute('aria-label','選択したレンタルスペース利用内容');summary.innerHTML=`<p class="eyebrow">SELECTED REQUEST</p><h2>選択した利用内容</h2><dl><div><dt>日付</dt><dd>${esc(params.get('date'))}</dd></div><div><dt>時間</dt><dd>${esc(start)}${end?` – ${esc(end)}`:''}</dd></div><div><dt>利用目的</dt><dd>${esc(purpose)||'未選択'}</dd></div><div><dt>利用人数</dt><dd>${guests?`${esc(guests)}名`:'未選択'}</dd></div></dl><a href="./space.html#availability">日時を選び直す ↗</a>`;contact.prepend(summary);}contact.onsubmit=e=>{e.preventDefault();const data=new FormData(contact);if(!String(data.get('name')).trim()||!String(data.get('message')).trim()){notify('お名前とお問い合わせ内容を入力してください。');return;}openDialog(`<p class="eyebrow">CONTACT — PREVIEW</p><h2 id="dialog-title">入力内容の確認</h2><dl class="detail-meta"><dt>種別</dt><dd>${esc(data.get('type'))}</dd><dt>お名前</dt><dd>${esc(data.get('name'))}</dd><dt>メール</dt><dd>${esc(data.get('email'))}</dd></dl><div class="article-body">${esc(data.get('message'))}</div><div class="notice">デモフォームのため、この内容は送信されません。</div><button class="button light" id="contact-done">確認を完了（送信しません） <span>↗</span></button><button class="button outline" id="contact-back">入力内容を修正 <span>←</span></button>`);$('#contact-back').onclick=closeDialog;$('#contact-done').onclick=()=>{openDialog('<div class="success-icon">✓</div><h2 id="dialog-title">入力内容を確認しました。</h2><p>デモ体験はここまでです。\n内容は送信・保存されていません。</p><button class="button light" id="contact-close">フォームへ戻る <span>↗</span></button>');$('#contact-close').onclick=closeDialog;};};}
renderEvents();renderJournal();const articleId=new URLSearchParams(location.search).get('article');if(articleId)showArticle(articleId);
