const $=(q,el=document)=>el.querySelector(q), $$=(q,el=document)=>[...el.querySelectorAll(q)];
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const events=[
{id:'moon',category:'cinema',label:'映画上映',date:'2026.11.28 SAT',time:'18:30 開場 / 19:00 開始',title:'はじめましての上映会',description:'こまどの幕開けに、一本の映画を。上映作品は近日お知らせします。',body:'初めてお店に灯りがともる夜。上映の前も後も、一杯のコーヒーと一緒にお過ごしください。\n上映作品・上映時間は準備が整い次第お知らせします。現在は開催イメージを紹介するサンプルです。',price:1500,capacity:4},
{id:'jazz',category:'music',label:'音楽',date:'2026.11.29 SUN',time:'17:30 開場 / 18:00 開始',title:'日曜の夕暮れ、ふたりのジャズ。',description:'ピアノとギターをすぐそばで。小さな喫茶で楽しむ生演奏。',body:'大きなステージはありません。いつもの喫茶の椅子で、近くから届く音を楽しむ日曜日。\n出演者と演奏内容は正式公開時にご案内します。現在は開催イメージを紹介するサンプルです。',price:2800,capacity:4},
{id:'coffee',category:'workshop',label:'ワークショップ',date:'2026.12.05 SAT',time:'10:30 開場 / 11:00 開始',title:'朝のコーヒー教室',description:'豆を挽くところから、ゆっくりと。はじめての方もどうぞ。',body:'お湯を注いで、香りを待って。一杯のコーヒーをおいしく淹れる、小さなワークショップです。\n道具はお店で用意する想定です。講師や内容は正式公開時にご案内します。',price:2000,capacity:2}];
const defaultArticles=[
{id:'opening',date:'2026-10-01',category:'お知らせ',title:'11月末、こまどがオープンします。',body:'映画と、喫茶と、小さな集まり。\nシアター喫茶「こまど」は、11月末の開店を目指して準備中です。\n一本の映画を観に来る日も、コーヒーだけを飲みに来る日も。好きなものをきっかけに、気軽に立ち寄れる場所をつくります。\n正式な開店日・所在地・営業日時は、準備が整い次第こちらでご案内します。\n※店名を含め、制作プレビュー用の仮情報です。'},
{id:'about',date:'2026-10-03',category:'読みもの',title:'スクリーンのそばに、喫茶の席を。',body:'映画のあと、すぐに帰るのが少し惜しい。\nそんなときに、コーヒーを飲みながらもう少し過ごせる席があったら。\nこまどでは、映画のある日もない日も、それぞれの時間を楽しめる店を目指しています。上映会のほかにも、小さなライブやワークショップを開いていく予定です。\n店内の椅子やメニューのことも、これから少しずつお伝えしていきます。\n※提案用の記事サンプルです。'},
{id:'rental',date:'2026-10-05',category:'お知らせ',title:'小さな上映会や貸切のご相談について。',body:'好きな映画を一緒に観る会。音楽を届ける夜。誰かに教えたくなるワークショップ。\nこまどでは、空間を貸し出す準備を進めています。\nご希望の日程や人数、利用内容をお知らせいただき、設備と条件を確認してから正式な予約へ進む予定です。\n現在のカレンダー・定員・料金はサンプルです。実際のご相談受付は正式公開後に開始します。'}];
let articles=structuredClone(defaultArticles),storageAvailable=true,activeJournalFilter='all';
try{const saved=JSON.parse(localStorage.getItem('komado.articles.v1')||'null');if(Array.isArray(saved)&&saved.every(a=>a&&['id','date','category','title','body'].every(k=>typeof a[k]==='string')&&['お知らせ','読みもの'].includes(a.category)))articles=saved;}catch{storageAvailable=false;}
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
function animateState(el,move=false){el.getAnimations().forEach(a=>a.cancel());if(!reducedMotion.matches)el.animate([{opacity:.55,transform:move?'translateY(4px)':'none'},{opacity:1,transform:'none'}],{duration:move?220:160,easing:'cubic-bezier(.2,.7,.2,1)'});}
const titleMarkup=e=>esc(e.title);
let lastFocus;const dialog=$('#dialog');
function openDialog(html){if(!dialog.open)lastFocus=document.activeElement;$('#dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal();document.body.classList.add('body-lock');animateState($('#dialog-content'),true);const title=$('#dialog-title');if(title){title.tabIndex=-1;title.focus();}}
function closeDialog(){dialog.close();}
dialog.addEventListener('close',()=>{document.body.classList.remove('body-lock');$('#dialog-content').getAnimations().forEach(a=>a.cancel());lastFocus?.focus();});$('.dialog-close').onclick=closeDialog;
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function notify(message){const el=$('.toast');el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),3500);}
const menu=$('.menu-toggle');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');$('#navigation').classList.toggle('open',open);};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.click();menu.focus();}});
$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')&&menu.getAttribute('aria-expanded')==='true')menu.click();});
function renderEvents(filter='all'){
 $$('[data-event-list]').forEach(list=>{
  list.innerHTML=events.filter(e=>filter==='all'||e.category===filter).map(e=>{
   const parts=e.date.split(/[. ]/),day=e.id==='jazz'?'日':'土',start=e.time.split(' / ')[1].replace(' 開始','');
   return `<article class="event-card"><time class="event-date" datetime="${parts.slice(0,3).join('-')}"><span>${Number(parts[1])}月</span><strong>${parts[2]}</strong><small>${day}曜日</small></time><div class="event-info"><span class="event-category">${e.label}</span><h3>${titleMarkup(e)}</h3><p class="event-summary">${esc(e.description)}</p></div><div class="event-meta"><span>${start} 開始</span><strong>¥${e.price.toLocaleString()}</strong><small>1名・税込（仮）</small></div><button class="event-link" data-event="${e.id}" aria-label="${esc(e.title)} の詳細・予約">詳細・予約 <span aria-hidden="true">↗</span></button></article>`;
  }).join('');
 });
}
$$('[data-filter]').forEach(btn=>btn.onclick=()=>{$$('[data-filter]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});renderEvents(btn.dataset.filter);});
function showEvent(id,count=1){const e=events.find(e=>e.id===id);if(!e)return;openDialog(`<p class="eyebrow">${e.label} — EVENT DETAILS</p><h2 id="dialog-title">${titleMarkup(e)}</h2><p>${e.body}</p><dl class="detail-meta"><dt>開催日</dt><dd>${e.date}</dd><dt>時間</dt><dd>${e.time}</dd><dt>料金</dt><dd>¥${e.price.toLocaleString()} / 1名・税込（仮）</dd></dl><div class="notice">予約体験のデモです。席の確保・決済は行いません。</div><form id="event-form"><label>ご予約人数<select name="count">${Array.from({length:e.capacity},(_,i)=>`<option value="${i+1}" ${count===i+1?'selected':''}>${i+1}名</option>`).join('')}</select></label><p id="booking-total">合計 ¥${(e.price*count).toLocaleString()}（税込・仮）</p><button class="button light" type="submit">予約内容を確認 <span>↗</span></button></form>`);const form=$('#event-form');form.elements.count.onchange=()=>$('#booking-total').textContent=`合計 ¥${(Number(form.elements.count.value)*e.price).toLocaleString()}（税込・仮）`;form.onsubmit=ev=>{ev.preventDefault();showBookingConfirmation(e,Number(form.elements.count.value));};}
function showBookingConfirmation(e,count){openDialog(`<p class="eyebrow">RESERVATION PREVIEW</p><h2 id="dialog-title"><span class="keep-phrase">予約内容を</span><span class="keep-phrase">ご確認ください。</span></h2><dl class="detail-meta"><dt>イベント</dt><dd>${e.title}</dd><dt>開催日</dt><dd>${e.date}</dd><dt>時間</dt><dd>${e.time}</dd><dt>人数</dt><dd>${count}名</dd><dt>合計</dt><dd>¥${(e.price*count).toLocaleString()}（税込・仮）</dd></dl><div class="notice">予約体験のデモです。実際の予約は成立しません。</div><button class="button light" id="finish-demo">予約のデモを完了 <span>↗</span></button><button class="button outline" id="back-booking">人数を選び直す <span>←</span></button>`);$('#back-booking').onclick=()=>showEvent(e.id,count);$('#finish-demo').onclick=()=>{openDialog(`<div class="success-icon">✓</div><p class="eyebrow">DEMO COMPLETED</p><h2 id="dialog-title">予約の流れを体験しました。</h2><p>ご選択内容：${e.title}\n${count}名 / ¥${(e.price*count).toLocaleString()}（税込・仮）</p><div class="notice">実際の予約は作成されていません。お支払いや確認メールの送信も行っていません。</div><button class="button light" id="done-close">イベントへ戻る <span>↗</span></button>`);$('#done-close').onclick=closeDialog;};}
function renderJournal(){$$('[data-journal-list]').forEach(list=>{const limit=Number(list.dataset.limit)||1000;list.innerHTML=[...articles].filter(a=>activeJournalFilter==='all'||a.category===activeJournalFilter).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,limit).map(a=>`<button class="journal-row" data-article="${esc(a.id)}"><time datetime="${esc(a.date)}">${esc(a.date.replaceAll('-','.'))}</time><span class="journal-tag">${esc(a.category)}</span><span class="journal-title">${esc(a.title).replace(/(オープンします。)$/,'<span class="keep-phrase">$1</span>')}</span><span class="arrow">↗</span></button>`).join('')||'<p>該当する記事はありません。</p>';});}
function showArticle(id){const a=articles.find(a=>a.id===id);if(a)openDialog(`<p class="eyebrow">${esc(a.date.replaceAll('-','.'))} / ${esc(a.category)}</p><h2 id="dialog-title">${esc(a.title).replace(/(こまどが|オープンします。|喫茶の席を。|ご相談について。)/g,'<span class="keep-phrase">$1</span>')}</h2><div class="article-body">${esc(a.body)}</div>`);}
$$('[data-journal-filter]').forEach(btn=>btn.onclick=()=>{activeJournalFilter=btn.dataset.journalFilter;$$('[data-journal-filter]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});renderJournal();});
document.addEventListener('click',e=>{const event=e.target.closest('[data-event]'),article=e.target.closest('[data-article]'),privacy=e.target.closest('[data-privacy]');if(event)showEvent(event.dataset.event);if(article)showArticle(article.dataset.article);if(privacy)openDialog('<p class="eyebrow">PRIVACY — PREVIEW</p><h2 id="dialog-title">プライバシーについて</h2><p>この制作プレビューでは、お問い合わせ内容をサーバーへ送信・保存しません。予約操作もデモです。\n\n記事管理デモで保存した記事は、このブラウザーのローカルストレージに保存されます。記事本文に個人情報や機密情報を入力しないでください。サイトデータを削除すると記事も削除されます。\n\n書体の表示にGoogle Fontsを使用し、フォント取得時に同サービスへ接続します。\n\n正式公開時には、実際の運営者情報・利用目的・保存期間・お問い合わせ窓口を定めたプライバシーポリシーを掲載します。</p>');});
const editor=$('#editor');
if(editor){const form=$('#editor-form');function refreshOptions(){$('#edit-id').innerHTML='<option value="">新しい記事を追加</option>'+articles.map(a=>`<option value="${esc(a.id)}">${esc(a.title)}</option>`).join('');}function clear(){form.reset();form.elements.date.value=new Date().toLocaleDateString('sv-SE');}refreshOptions();clear();$('#open-editor').onclick=()=>{editor.hidden=!editor.hidden;$('#open-editor').setAttribute('aria-expanded',String(!editor.hidden));if(!editor.hidden){editor.scrollIntoView({behavior:reducedMotion.matches?'instant':'smooth',block:'start'});$('#edit-id').focus({preventScroll:true});}};$('#edit-id').onchange=()=>{const a=articles.find(a=>a.id===$('#edit-id').value);if(a){for(const k of ['title','category','date','body'])form.elements[k].value=a[k];}else clear();};form.onsubmit=e=>{e.preventDefault();const data=new FormData(form),title=String(data.get('title')).trim(),body=String(data.get('body')).trim();if(!title||!body){$('#editor-status').textContent='タイトルと本文を入力してください。';return;}const id=$('#edit-id').value||crypto.randomUUID(),article={id,title,body,category:String(data.get('category')),date:String(data.get('date'))};const updated=articles.some(a=>a.id===id)?articles.map(a=>a.id===id?article:a):[...articles,article];try{localStorage.setItem('komado.articles.v1',JSON.stringify(updated));articles=updated;renderJournal();refreshOptions();$('#edit-id').value=id;$('#editor-status').textContent='このブラウザーに保存しました。サイトへの公開は行われていません。';notify('記事をこのブラウザーに保存しました');}catch{$('#editor-status').textContent='保存できませんでした。ブラウザーの保存設定や空き容量を確認してください。';}};$('#export-content').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,articles},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='komado-articles.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};if(!storageAvailable)$('#editor-status').textContent='保存データを読み込めなかったため初期記事を表示しています。';}
let calendarDate=new Date(2026,10,1),selectedDate='';const calendar=$('#calendar-grid'),firstDate=new Date(2026,10,28),lastDate=new Date(2027,10,30);
function availability(day){if(day<firstDate||day>lastDate||day.getDay()===2)return 0;return day.getDate()%3===0?1:2;}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#calendar-month').textContent=`${y}年 ${m+1}月`;$('[data-month="-1"]').disabled=y===2026&&m===10;$('[data-month="1"]').disabled=y===2027&&m===10;calendar.innerHTML=Array.from({length:new Date(y,m,1).getDay()},()=>'<span></span>').join('')+Array.from({length:new Date(y,m+1,0).getDate()},(_,i)=>{const available=availability(new Date(y,m,i+1)),iso=`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return `<button class="calendar-day ${selectedDate===iso?'selected':''}" data-date="${iso}" ${available?'':'disabled'} aria-pressed="${selectedDate===iso}" aria-label="${y}年${m+1}月${i+1}日 ${available===2?'空きあり':available===1?'一部空き':'受付なし'}">${i+1}<small>${available===2?'○':available===1?'△':'—'}</small></button>`;}).join('');}
if(calendar){renderCalendar();$$('[data-month]').forEach(btn=>btn.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+Number(btn.dataset.month));selectedDate='';renderCalendar();animateState(calendar);$('#time-slots').innerHTML='<p class="muted">カレンダーから日付を選んでください。</p>';});calendar.onclick=e=>{const btn=e.target.closest('[data-date]');if(!btn||btn.disabled)return;selectedDate=btn.dataset.date;renderCalendar();calendar.querySelector(`[data-date="${selectedDate}"]`).focus({preventScroll:true});const a=availability(new Date(`${selectedDate}T12:00:00`)),slots=a===1?['14:00 – 17:00']:['10:00 – 13:00','14:00 – 17:00','18:00 – 21:00'];$('#time-slots').innerHTML=`<p>${selectedDate.replaceAll('-',' / ')} — ご希望の時間帯を選択</p><div class="slots">${slots.map(slot=>`<button class="slot" data-slot="${slot}">${slot} ↗</button>`).join('')}</div>`;animateState($('#time-slots'));};$('#time-slots').onclick=e=>{const btn=e.target.closest('[data-slot]');if(!btn)return;const slot=btn.dataset.slot;openDialog(`<p class="eyebrow">SPACE RENTAL — PREVIEW</p><h2 id="dialog-title">この時間で、相談する。</h2><dl class="detail-meta"><dt>ご希望日</dt><dd>${selectedDate.replaceAll('-',' / ')}</dd><dt>時間帯</dt><dd>${slot}</dd><dt>参考料金</dt><dd>¥12,000 / 3時間（仮・税込）</dd></dl><p>ご相談内容を確認後、担当者との打ち合わせを経て正式なご予約となる想定です。</p><div class="notice">空き状況はサンプルです。予約は確定しません。</div><a class="button light" href="./contact.html?date=${selectedDate}&slot=${encodeURIComponent(slot)}">利用内容の相談へ <span>↗</span></a>`);};}
const contact=$('#contact-form');if(contact){const params=new URLSearchParams(location.search);if(params.has('date')){contact.elements.type.value='スペースレンタルについて';contact.elements.message.value=`希望日：${params.get('date')}\n希望時間：${params.get('slot')||''}\n利用目的：\n予定人数：\nご相談内容：`;}contact.onsubmit=e=>{e.preventDefault();const data=new FormData(contact);if(!String(data.get('name')).trim()||!String(data.get('message')).trim()){notify('お名前とお問い合わせ内容を入力してください。');return;}openDialog(`<p class="eyebrow">CONTACT — PREVIEW</p><h2 id="dialog-title">入力内容の確認</h2><dl class="detail-meta"><dt>種別</dt><dd>${esc(data.get('type'))}</dd><dt>お名前</dt><dd>${esc(data.get('name'))}</dd><dt>メール</dt><dd>${esc(data.get('email'))}</dd></dl><div class="article-body">${esc(data.get('message'))}</div><div class="notice">デモフォームのため、この内容は送信されません。</div><button class="button light" id="contact-done">確認を完了（送信しません） <span>↗</span></button><button class="button outline" id="contact-back">入力内容を修正 <span>←</span></button>`);$('#contact-back').onclick=closeDialog;$('#contact-done').onclick=()=>{openDialog('<div class="success-icon">✓</div><h2 id="dialog-title">入力内容を確認しました。</h2><p>デモ体験はここまでです。\n内容は送信・保存されていません。</p><button class="button light" id="contact-close">フォームへ戻る <span>↗</span></button>');$('#contact-close').onclick=closeDialog;};};}
renderEvents();renderJournal();const articleId=new URLSearchParams(location.search).get('article');if(articleId)showArticle(articleId);
